"""``run.sh``: generated by ``xewe setup`` so it never drifts from the tools.

``xewe setup`` writes ``<root>/run.sh`` on every run: in a project ``RUN_SH`` (``xewe run``, the
manifest's default chip filled in), in a library ``CHECK_SH`` (``xewe check``). Both carry the
installed tools version. ``run.sh`` is not committed; ``setup.sh`` generates it.
"""

from __future__ import annotations

import os
from pathlib import Path

from xewe import __version__
from xewe.env.project import Paths, write_atomic
from xewe.report import log

GENERATED_MARK = "# generated by xewe setup; do not edit"

RUN_SH = """\
#!/usr/bin/env bash
{mark} (xewe-os-tools {version}; ./setup.sh rewrites it).
# run.sh: build, erase the flash, flash, then listen on the serial console (`xewe run`).
#   chip: {chip} unless --chip C (default from xewe.toml [project] chip)
#   every run erases the whole flash, NVS included (device name, Wi-Fi, module choices), so the
#   board boots as new; --keep-nvs skips the erase. All flags: ./run.sh --help
set -euo pipefail
ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
PY="${{ROOT}}/build/tools/.venv/bin/python"
[[ -x "${{PY}}" ]] || {{ echo "error: run ./setup.sh first" >&2; exit 3; }}
exec "${{PY}}" -m xewe --project "${{ROOT}}" run "$@"
"""

CHECK_SH = """\
#!/usr/bin/env bash
{mark} (xewe-os-tools {version}; ./setup.sh rewrites it).
# run.sh: the library's checks (`xewe check`): the host unit tests (tests/unit/run.sh), then every
#   example compiled with the template's board options for c3, unless --chip C or --all-chips.
#   --unit or --examples runs one part. All flags: ./run.sh --help
set -euo pipefail
ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
PY="${{ROOT}}/build/tools/.venv/bin/python"
[[ -x "${{PY}}" ]] || {{ echo "error: run ./setup.sh first" >&2; exit 3; }}
exec "${{PY}}" -m xewe --project "${{ROOT}}" check "$@"
"""


def render(chip: str, version: str = __version__) -> str:
    """The project ``run.sh`` for a project whose default chip is ``chip``."""
    return RUN_SH.format(mark=GENERATED_MARK, version=version, chip=chip)


def render_check(version: str = __version__) -> str:
    """The library ``run.sh``."""
    return CHECK_SH.format(mark=GENERATED_MARK, version=version)


def write(p: Paths, text: str) -> None:
    """Write ``<root>/run.sh`` (mode 755) with ``text``, replacing whatever is there."""
    path = p.root / "run.sh"
    if path.is_file() and not path.is_symlink() and path.read_text(encoding="utf-8", errors="replace") == text:
        log.debug("run.sh is current")
    else:
        if path.is_symlink():
            path.unlink()
        write_atomic(path, text)
        log.info("wrote %s (generated)", p.rel(path))
    _executable(path)


def _executable(path: Path) -> None:
    mode = path.stat().st_mode
    if mode & 0o111 != 0o111:
        os.chmod(path, mode | 0o755)
