import logging
import shutil
from pathlib import Path

import pytest

from conftest import make_modules_checkout
from xewe.cli import main
from xewe.env.project import Paths
from xewe.modules import registry as modules
from xewe.modules.registry import Registry
from xewe.report import XeWeError

MODULES_H = """\
// Generated by xewe modules generate; do not edit. Re-run ./setup.sh or `xewe modules select` to change modules.
// Included by the sketch after `os`; modules are declared in dependency order.
#pragma once

#include <XeWeModules.h>

Wifi wifi(os);
Time time_module(os, wifi);
Scheduler scheduler(os, time_module);
WebInterface web_interface(os, wifi);
"""

XEWE_MODULES_H = """\
// Generated by xewe modules generate; do not edit. The selected XeWe OS modules in dependency order.
#pragma once

#include "Wifi/Wifi.h"
#include "Time/Time.h"
#include "Scheduler/Scheduler.h"
#include "WebInterface/WebInterface.h"
"""

LIBRARY_PROPERTIES = """\
name=XeWeModules
version=v1.0.0
author=xewe-labs
maintainer=xewe-labs
sentence=The XeWe OS modules selected for this project; generated by xewe modules generate, do not edit.
paragraph=Modules: wifi, web-interface.
category=Other
url=https://github.com/xewe-labs/xewe-os-modules
architectures=esp32
depends=XeWeCore
includes=XeWeModules.h
"""
LOCK_HEADER = "# generated by xewe: slug|folder|source|ref|commit\n"


@pytest.fixture(params=["modules", "legacy"])
def checkout(request: pytest.FixtureRequest, tmp_path: Path) -> Path:
    return make_modules_checkout(tmp_path / "checkout", request.param)


def _set(checkout: Path, slug: str, key: str, value: str | None) -> None:
    props = next(checkout.rglob(f"*{slug}/module.properties"))
    lines = [ln for ln in props.read_text().splitlines() if not ln.startswith(f"{key}=")]
    if value is not None:
        lines.insert(0, f"{key}={value}")
    props.write_text("\n".join(lines) + "\n")


def test_registry_reads_both_layouts(checkout: Path) -> None:
    reg = Registry.load(checkout)
    assert reg.slugs() == ["buttons", "pins", "scheduler", "time", "web-interface", "wifi"]


def test_properties_first_key_wins() -> None:
    props, keys = modules.parse_properties("a=1\na=2\nb=x=y\n# c=3\n")
    assert props == {"a": "1", "b": "x=y"} and keys == ["a", "a", "b"]


def test_resolve_order_and_additions(checkout: Path, caplog: pytest.LogCaptureFixture) -> None:
    with caplog.at_level(logging.INFO, logger="xewe"):
        order = Registry.load(checkout).resolve(["scheduler", "web-interface"])
    assert [m.slug for m in order] == ["wifi", "time", "scheduler", "web-interface"]
    assert "scheduler requires time; adding it" in caplog.text
    assert "time requires wifi; adding it" in caplog.text
    assert modules.render_modules_h(order) == MODULES_H
    assert modules.render_library_h(order) == XEWE_MODULES_H


def test_cycle_is_an_error(checkout: Path) -> None:
    _set(checkout, "wifi", "depends_modules", "scheduler")
    with pytest.raises(XeWeError, match="dependency cycle through module"):
        Registry.load(checkout).resolve(["scheduler"])


def test_unknown_module_is_usage_error(checkout: Path) -> None:
    with pytest.raises(XeWeError) as exc:
        Registry.load(checkout).resolve(["nope"])
    assert exc.value.code == 2


def test_generate_writes_modules(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    order = modules.generate(p, Registry.load(checkout), ["wifi", "web-interface"], "https://x/mods", "v1.0.0", "c0ffee")
    assert [m.slug for m in order] == ["wifi", "web-interface"]
    assert sorted(f.name for f in p.modules.iterdir()) == ["library.properties", "modules.lock", "src"]
    assert sorted(f.name for f in (p.modules / "src").iterdir()) == ["WebInterface", "Wifi", "XeWeModules.h"]
    assert (p.modules / "src" / "Wifi" / "Wifi.h").is_file()
    assert (p.modules / "library.properties").read_text() == LIBRARY_PROPERTIES
    assert (p.modules / "src" / "XeWeModules.h").read_text().endswith(
        '#include "Wifi/Wifi.h"\n#include "WebInterface/WebInterface.h"\n')
    text = p.src_modules_h.read_text()
    assert text.startswith("// Generated by xewe modules generate; do not edit.")
    assert text.endswith("#include <XeWeModules.h>\n\nWifi wifi(os);\nWebInterface web_interface(os, wifi);\n")
    assert p.modules_lock.read_text() == (
        LOCK_HEADER
        + "wifi|Wifi|https://x/mods|v1.0.0|c0ffee\n"
        "web-interface|WebInterface|https://x/mods|v1.0.0|c0ffee\n"
    )
    assert p.modules_lock == p.root / "build" / "modules" / "modules.lock"
    assert sorted(f.name for f in p.root.iterdir()) == ["build", "src"]
    assert sorted(f.name for f in (p.root / "src").iterdir()) == ["Modules.h"]  # no src/modules/ any more
    assert sorted(f.name for f in p.build.iterdir()) == ["modules"]  # staging swapped away, build/tmp removed


def test_library_version_falls_back_to_commit(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    modules.generate(p, Registry.load(checkout), ["wifi"], "local:/x", "-", "c0ffee")
    assert "\nversion=c0ffee\n" in (p.modules / "library.properties").read_text()


def test_generate_empty_selection(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    modules.generate(p, Registry.load(checkout), ["wifi"], "s", "r", "c")
    assert modules.generate(p, Registry.load(checkout), [], "https://x/mods", "v1.0.0", "c0ffee") == []
    assert sorted(f.name for f in p.modules.iterdir()) == ["library.properties", "modules.lock", "src"]
    assert sorted(f.name for f in (p.modules / "src").iterdir()) == ["XeWeModules.h"]
    props = (p.modules / "library.properties").read_text()
    assert "name=XeWeModules\n" in props and "paragraph=Modules: none.\n" in props
    lib_h = (p.modules / "src" / "XeWeModules.h").read_text()
    assert "#pragma once\n" in lib_h and "#include" not in lib_h
    text = p.src_modules_h.read_text()
    assert text.startswith("// Generated by xewe modules generate") and "#pragma once\n" in text
    assert "#include <XeWeModules.h>\n" in text and text.count("#include") == 1 and "(os" not in text
    assert p.modules_lock.read_text() == LOCK_HEADER


def test_generate_copies_module_tests(tmp_path: Path) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules", board_tests=True)
    wifi = checkout / "modules" / "wifi" / "tests"
    (wifi / "unit").mkdir()
    (wifi / "unit" / "test_logic.py").write_text("")
    (wifi / "board" / "__pycache__").mkdir()
    p = Paths(tmp_path / "proj")
    modules.generate(p, Registry.load(checkout), ["web-interface"], "s", "r", "c")  # wifi comes as a dependency
    assert sorted(f.name for f in p.modules.iterdir()) == ["library.properties", "modules.lock", "src", "tests"]
    assert sorted(f.name for f in (p.modules / "tests").iterdir()) == ["web-interface", "wifi"]
    assert sorted(f.name for f in p.module_tests("wifi").iterdir()) == ["board", "unit"]
    assert sorted(f.name for f in (p.module_tests("wifi") / "board").iterdir()) == ["test_wifi.py"]
    assert (p.module_tests("web-interface") / "board" / "test_web-interface.py").is_file()
    # a new selection replaces the tests too
    modules.generate(p, Registry.load(checkout), ["pins"], "s", "r", "c")
    assert sorted(f.name for f in (p.modules / "tests").iterdir()) == ["pins"]


def test_module_dir_in_repo_and_from_project_copy(project: Paths, tmp_path: Path) -> None:
    from xewe.testing import module_dir

    wifi = tmp_path / "modules-src" / "modules" / "wifi"  # the recorded checkout (XEWE_MODULES_SOURCE)
    assert module_dir(wifi / "tests" / "unit" / "test_wifi.py") == wifi
    copy = project.module_tests("wifi") / "unit" / "test_wifi.py"
    copy.parent.mkdir(parents=True, exist_ok=True)
    copy.write_text("")
    assert module_dir(copy) == wifi


def test_generate_removes_previous_layout(tmp_path: Path, checkout: Path, capsys: pytest.CaptureFixture[str]) -> None:
    p = Paths(tmp_path / "proj")
    (p.build / "modules-lib" / "src").mkdir(parents=True)
    (p.build / "modules" / "modules").mkdir(parents=True)  # the old in-project modules checkout
    p.config_dir.mkdir()
    (p.config_dir / "modules.lock").write_text(LOCK_HEADER)
    modules.generate(p, Registry.load(checkout), ["wifi"], "s", "r", "c")
    assert sorted(f.name for f in p.build.iterdir()) == ["config", "modules"]
    assert list(p.config_dir.iterdir()) == []
    assert sorted(f.name for f in p.modules.iterdir()) == ["library.properties", "modules.lock", "src"]
    out = capsys.readouterr().out
    assert "removed legacy build/modules-lib" in out and "removed legacy build/config/modules.lock" in out


def test_generate_removes_legacy_src_modules(tmp_path: Path, checkout: Path, capsys: pytest.CaptureFixture[str]) -> None:
    p = Paths(tmp_path / "proj")
    legacy = p.root / "src" / "modules"
    (legacy / "Wifi").mkdir(parents=True)
    (legacy / "Modules.h").write_text("// old\n")
    (legacy / "modules.lock").write_text(LOCK_HEADER + "wifi|Wifi|s|r|c\n")
    modules.generate(p, Registry.load(checkout), ["wifi"], "s", "r", "c")
    assert not legacy.exists()
    assert "removed legacy src/modules/" in capsys.readouterr().out


@pytest.mark.parametrize("lock_text", [None, "# my own notes\n", ""])
def test_generate_keeps_src_modules_it_did_not_write(tmp_path: Path, checkout: Path, lock_text: str | None,
                                                     capsys: pytest.CaptureFixture[str]) -> None:
    p = Paths(tmp_path / "proj")
    own = p.root / "src" / "modules"
    own.mkdir(parents=True)
    (own / "Mine.h").write_text("// the owner's code\n")
    if lock_text is not None:
        (own / "modules.lock").write_text(lock_text)
    modules.generate(p, Registry.load(checkout), ["wifi"], "s", "r", "c")
    assert (own / "Mine.h").is_file()
    assert "removed legacy" not in capsys.readouterr().out


@pytest.mark.parametrize("value", ["", "none", " none "])
def test_expand_selection_none(checkout: Path, value: str) -> None:
    assert modules.expand_selection(Registry.load(checkout), value) == []


def test_failed_generate_keeps_old_modules(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    reg = Registry.load(checkout)
    modules.generate(p, reg, ["wifi"], "s", "r", "c")
    shutil.rmtree(next(checkout.rglob("*pins/src")))
    with pytest.raises(XeWeError):
        modules.generate(p, Registry.load(checkout), ["pins"], "s", "r", "c")
    assert (p.modules / "src" / "Wifi").is_dir()
    assert "Wifi wifi(os);" in p.src_modules_h.read_text()


def test_real_properties_validate_clean(checkout: Path) -> None:
    assert modules.validate(Registry.load(checkout), core_ref="1.0.0") == []


@pytest.mark.parametrize(("slug", "key", "value", "message"), [
    ("wifi", "slug", "Wifi", "must match"),
    ("pins", "slug", "buttons", "is not unique"),
    ("pins", "slug", "pinz", "does not match its directory"),
    ("wifi", "id", "Wifi", "must match"),
    ("wifi", "id", "a_sixteen_chars_", "NVS namespace limit"),
    ("pins", "id", "buttons", "is not unique"),
    ("wifi", "folder", "wifi", "must match"),
    ("pins", "folder", "Buttons", "is not unique"),
    ("wifi", "folder", "Wireless", "does not exist"),
    ("wifi", "include", "Wifi.h", "must start with src/Wifi/"),
    ("wifi", "include", "src/Wifi/Missing.h", "does not exist"),
    ("wifi", "declare", "Wifi wifi(os)", "must look like"),
    ("wifi", "declare", "Wifi os(os);", "must not be 'os'"),
    ("pins", "declare", "Pins wifi(os);", "is not unique"),
    ("web-interface", "declare", "WebInterface web_interface(os, scheduler);", "neither 'os' nor"),
    ("wifi", "depends_modules", "wifi", "lists the module itself"),
    ("wifi", "depends_modules", "nope", "unknown module 'nope'"),
    ("wifi", "depends_modules", "scheduler", "dependency cycle"),
    ("wifi", "requires_core", "1.0.0", "must be '>=X.Y.Z'"),
    ("wifi", "requires_core", ">=2.0.0", "is not satisfied by core 1.0.0"),
    ("wifi", "requires_core", ">=0.5.0,<1.0.0", "is not satisfied"),
    ("wifi", "version", "1.0", "must be X.Y.Z"),
    ("wifi", "description", "", "description is empty"),
    ("wifi", "description", "x" * 101, "max 100"),
    ("wifi", "name", None, "missing key 'name'"),
    ("wifi", "depends_libraries", None, "missing key 'requires_core'"),
])
def test_every_rule_has_a_failing_fixture(tmp_path: Path, slug: str, key: str, value: str | None, message: str) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "legacy")
    _set(checkout, slug, key, value)
    errors = [str(p) for p in modules.validate(Registry.load(checkout), core_ref="1.0.0") if p.error]
    assert any(message in e for e in errors), errors


def test_warnings_do_not_fail(tmp_path: Path) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules")
    _set(checkout, "wifi", "colour", "blue")
    _set(checkout, "wifi", "declare", "Wireless wifi(os);")
    problems = modules.validate(Registry.load(checkout))
    assert problems and not any(p.error for p in problems)


def test_requires_core_non_semver_ref_is_skipped(tmp_path: Path) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules")
    _set(checkout, "wifi", "requires_core", ">=9.0.0")
    assert modules.validate(Registry.load(checkout), core_ref="main") == []


def test_cli_validate_reference_layout(project: Paths, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    legacy = make_modules_checkout(tmp_path / "legacy", "legacy", board_tests=True)
    assert main(["modules", "validate", str(legacy)]) == 0
    assert "6 modules, 0 errors" in capsys.readouterr().out
    _set(legacy, "wifi", "id", "a_sixteen_chars_")
    assert main(["modules", "validate", str(legacy)]) == 1


def test_cli_list_select_generate(project: Paths, capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["modules", "list"]) == 0
    out = capsys.readouterr().out
    assert "* wifi" in out and "  pins" in out
    assert main(["modules", "select", "scheduler"]) == 0
    assert 'selected = ["scheduler"]' in project.lock.read_text()
    assert (project.modules / "src" / "XeWeModules.h").read_text().count("#include") == 3
    assert project.src_modules_h.read_text().count("(os") == 3
    assert main(["modules", "select", "nope"]) == 2
    assert main(["modules", "select", "none"]) == 0
    assert "selected = []" in project.lock.read_text()
    assert "(os" not in project.src_modules_h.read_text()
    assert "#include" not in (project.modules / "src" / "XeWeModules.h").read_text()
    assert "modules: none  (build/modules, src/Modules.h)" in capsys.readouterr().out


def test_tests_layout_clean(tmp_path: Path) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules", board_tests=True)
    (checkout / "modules" / "wifi" / "tests" / "unit").mkdir()
    (checkout / "modules" / "wifi" / "tests" / "unit" / "test_wifi.py").write_text("")
    (checkout / "modules" / "wifi" / "tests" / "board" / "__pycache__").mkdir()
    assert modules.check_tests_layout(Registry.load(checkout)) == []


@pytest.mark.parametrize(("entry", "message"), [
    ("tests/test_wifi.py", "tests/test_wifi.py not allowed"),
    ("tests/host/test_x.cpp", "tests/host not allowed"),
    ("tests/conftest.py", "tests/conftest.py not allowed"),
    ("tests/board/conftest.py", "tests/board/conftest.py not allowed"),
    ("tests/unit/__init__.py", "tests/unit/__init__.py not allowed"),
    ("tests/unit", "tests/board/test_wifi.py missing"),
])
def test_tests_layout_rules(tmp_path: Path, entry: str, message: str) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules", board_tests=True)
    wifi = checkout / "modules" / "wifi"
    if message.endswith("missing"):
        (wifi / "tests" / "board" / "test_wifi.py").unlink()
    path = wifi / entry
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix:
        path.write_text("")
    else:
        path.mkdir(exist_ok=True)
    errors = [str(p) for p in modules.check_tests_layout(Registry.load(checkout)) if p.error]
    assert any(message in e and e.startswith("error: wifi:") for e in errors), errors


def test_cli_validate_checks_tests_layout(project: Paths, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules")
    assert main(["modules", "validate", str(checkout)]) == 1
    assert "error: wifi: tests/board/test_wifi.py missing" in capsys.readouterr().out
