import json
import shutil
from pathlib import Path

import pytest

from conftest import FIXTURES
from xewe import build
from xewe.cli import main
from xewe.project import Paths

META_KEYS = [
    "type", "chip_family", "project_name", "version", "timestamp_param", "config", "fqbn", "fqbn_extra",
    "compile_time_sec", "artifacts", "tools_version", "arduino_cli", "esp32_core", "core_ref", "modules_ref",
    "modules", "sketch_size", "sketch_size_percent", "warnings",
]


def test_build_outputs(project: Paths, capsys: pytest.CaptureFixture[str], fake_cli: object) -> None:
    assert main(["build", "--chip", "c3"]) == 0
    out = project.out / "c3"
    assert sorted(f.name for f in out.iterdir()) == ["2.0.15-c3-xewe-os.bin", "build.stamp", "compile.log", "manifest.json",
                                                         "meta.json"]
    assert "Sketch uses 1123456 bytes (85%)  1 warnings" in capsys.readouterr().out
    golden = (FIXTURES / "manifest-2.0.0-c3.json").read_text().replace("2.0.0", "2.0.15")
    assert (out / "manifest.json").read_text() == golden
    meta = json.loads((out / "meta.json").read_text())
    assert list(meta) == META_KEYS
    assert meta["artifacts"] == {
        "binary_filename": "2.0.15-c3-xewe-os.bin",
        "path_rel_binary": "xewe-os/build/out/c3/2.0.15-c3-xewe-os.bin",
        "path_rel_manifest_json": "xewe-os/build/out/c3/manifest.json",
        "path_rel_meta_json": "xewe-os/build/out/c3/meta.json",
    }
    assert meta["sketch_size"] == 1123456 and meta["sketch_size_percent"] == 85 and meta["warnings"] == 1
    assert meta["modules"] == {"selected": ["wifi", "web-interface"], "resolved": ["wifi", "web-interface"]}
    assert "JTAGAdapter" not in meta["fqbn"]


def test_build_info_header_and_defines(project: Paths, fake_cli: object) -> None:
    assert main(["build", "--chip", "s3", "--define", "LED_PIN=8", "--define", 'WIFI_SSID="net"']) == 0
    header = (project.gen / "s3/XeWeBuildInfo/src/XeWeBuildInfo.h").read_text().splitlines()
    assert header[:3] == ["// generated by xewe build; do not edit", "#pragma once", '#define PROJECT_NAME "xewe-os"']
    assert header[3] == '#define BUILD_VERSION "2.0.15"'
    assert header[4].startswith('#define BUILD_TIMESTAMP "20')
    assert header[5:] == ['#define BUILD_CHIP "s3"', "#define LED_PIN 8", '#define WIFI_SSID "net"']
    assert (project.gen / "s3/XeWeBuildInfo/library.properties").read_text().startswith("name=XeWeBuildInfo\n")
    meta = json.loads((project.out / "s3/meta.json").read_text())
    assert meta["config"] == {"LED_PIN": 8, "WIFI_SSID": '"net"'}


def test_bad_define_is_usage_error(project: Paths) -> None:
    assert main(["build", "--define", "1BAD=2"]) == 2


def test_not_set_up_is_exit_3(project: Paths) -> None:
    project.build_config.unlink()
    assert main(["build"]) == 3


def test_parse_size_from_compile_log(tmp_path: Path) -> None:
    log = tmp_path / "compile.log"
    log.write_text(
        "Using library XeWeCore at version 1.0.0 in folder: build/libraries/XeWeCore\n"
        "Sketch uses 223406 bytes (17%) of program storage space. Maximum is 1310720 bytes.\n"
        "Global variables use 13240 bytes (4%) of dynamic memory, leaving 314440 bytes for local variables.\n"
    )
    assert build.parse_size(log.read_text()) == (223406, 17)
    assert build.parse_size("Sketch uses 10 bytes of program storage space.\n") == (10, None)
    assert build.parse_size("no size here") == (None, None)


def test_build_key_covers_defines_version_chip() -> None:
    base = build.build_key("c3", "2.0.15", {"A": "1", "B": "2"})
    assert base == build.build_key("c3", "2.0.15", {"B": "2", "A": "1"})
    assert base != build.build_key("c3", "2.0.15", {"A": "1"})
    assert base != build.build_key("c3", "2.0.15", {"A": "1", "B": "3"})
    assert base != build.build_key("c3", "2.0.16", {"A": "1", "B": "2"})
    assert base != build.build_key("s3", "2.0.15", {"A": "1", "B": "2"})


def test_zero_modules_builds(project: Paths, fake_cli: object) -> None:
    assert main(["modules", "select", "none"]) == 0
    assert main(["build", "--chip", "c3"]) == 0
    meta = json.loads((project.out / "c3/meta.json").read_text())
    assert meta["modules"] == {"selected": [], "resolved": []}


def test_missing_modules_h_is_exit_3(project: Paths) -> None:
    shutil.rmtree(project.src_modules)
    assert main(["build"]) == 3


def test_sketch_staging_when_folder_differs(tmp_path: Path, project: Paths, monkeypatch: pytest.MonkeyPatch,
                                            fake_cli) -> None:
    renamed = tmp_path / "my-firmware"
    shutil.move(str(project.root), str(renamed))
    monkeypatch.chdir(renamed)
    assert main(["build", "--chip", "c3"]) == 0
    staged = renamed / "build/gen/sketch/xewe-os"
    assert (staged / "xewe-os.ino").is_file() and (staged / "src/modules/Modules.h").is_file()
    assert (staged / "Config.h").stat().st_mtime == (renamed / "Config.h").stat().st_mtime
    assert not list(renamed.glob("my-firmware.ino"))
    assert (renamed / "build/out/c3/2.0.15-c3-xewe-os.bin").is_file()
    assert fake_cli()[-1]["argv"][-1] == "build/gen/sketch/xewe-os"


def test_all_chips_continues_after_failure(project: Paths, monkeypatch: pytest.MonkeyPatch,
                                           capsys: pytest.CaptureFixture[str], fake_cli) -> None:
    monkeypatch.setenv("FAKE_ARDUINO_COMPILE_FAIL", "esp32c6")
    assert main(["build", "--all-chips"]) == 1
    boards = [c["argv"][2].split(":")[2] for c in fake_cli() if c["argv"][0] == "compile"]
    assert boards == ["esp32c3", "esp32c6", "esp32s3"]
    assert (project.out / "s3/2.0.15-s3-xewe-os.bin").is_file()
    out = capsys.readouterr()
    assert "FAIL  c6" in out.out and "does not name a type" in out.err


def test_missing_merged_bin_fails(project: Paths, monkeypatch: pytest.MonkeyPatch,
                                  capsys: pytest.CaptureFixture[str]) -> None:
    monkeypatch.setenv("FAKE_ARDUINO_NO_MERGED", "1")
    assert main(["build", "--chip", "c3"]) == 1
    assert "core did not produce" in capsys.readouterr().err


def test_compile_env_and_cwd(project: Paths, fake_cli) -> None:
    assert main(["build", "--chip", "c3"]) == 0
    call = fake_cli()[-1]
    assert call["cwd"] == str(project.root)
    assert call["env"]["ARDUINO_DIRECTORIES_DATA"] == str(project.build / "arduino15")
