import logging
import shutil
from pathlib import Path

import pytest

from conftest import make_modules_checkout
from xewe import modules
from xewe.cli import main
from xewe.modules import Registry
from xewe.project import Paths
from xewe.report import XeweError

MODULES_H = """\
// Generated by xewe modules generate; do not edit. Re-run ./setup.sh or `xewe modules select` to change modules.
// Included by the sketch after `os`; modules are declared in dependency order.
#pragma once

#include "Wifi/Wifi.h"
#include "Time/Time.h"
#include "Scheduler/Scheduler.h"
#include "WebInterface/WebInterface.h"

Wifi wifi(os);
Time time_module(os, wifi);
Scheduler scheduler(os, time_module);
WebInterface web_interface(os, wifi);
"""


@pytest.fixture(params=["modules", "legacy"])
def checkout(request: pytest.FixtureRequest, tmp_path: Path) -> Path:
    return make_modules_checkout(tmp_path / "checkout", request.param)


def _set(checkout: Path, slug: str, key: str, value: str | None) -> None:
    props = next(checkout.rglob(f"*{slug}/module.properties"))
    lines = [ln for ln in props.read_text().splitlines() if not ln.startswith(f"{key}=")]
    if value is not None:
        lines.insert(0, f"{key}={value}")
    props.write_text("\n".join(lines) + "\n")


def test_registry_reads_both_layouts(checkout: Path) -> None:
    reg = Registry.load(checkout)
    assert reg.slugs() == ["buttons", "pins", "scheduler", "time", "web-interface", "wifi"]


def test_properties_first_key_wins() -> None:
    props, keys = modules.parse_properties("a=1\na=2\nb=x=y\n# c=3\n")
    assert props == {"a": "1", "b": "x=y"} and keys == ["a", "a", "b"]


def test_resolve_order_and_additions(checkout: Path, caplog: pytest.LogCaptureFixture) -> None:
    with caplog.at_level(logging.INFO, logger="xewe"):
        order = Registry.load(checkout).resolve(["scheduler", "web-interface"])
    assert [m.slug for m in order] == ["wifi", "time", "scheduler", "web-interface"]
    assert "scheduler requires time; adding it" in caplog.text
    assert "time requires wifi; adding it" in caplog.text
    assert modules.render_modules_h(order) == MODULES_H


def test_cycle_is_an_error(checkout: Path) -> None:
    _set(checkout, "wifi", "depends_modules", "scheduler")
    with pytest.raises(XeweError, match="dependency cycle through module"):
        Registry.load(checkout).resolve(["scheduler"])


def test_unknown_module_is_usage_error(checkout: Path) -> None:
    with pytest.raises(XeweError) as exc:
        Registry.load(checkout).resolve(["nope"])
    assert exc.value.code == 2


def test_generate_writes_modules_dir(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    order = modules.generate(p, Registry.load(checkout), ["wifi", "web-interface"], "https://x/mods", "v1.0.0", "c0ffee")
    assert [m.slug for m in order] == ["wifi", "web-interface"]
    assert sorted(f.name for f in p.src_modules.iterdir()) == [".gitignore", "Modules.h", "WebInterface", "Wifi", "modules.lock"]
    assert (p.src_modules / "modules.lock").read_text() == (
        "# generated by xewe: slug|folder|source|ref|commit\n"
        "wifi|Wifi|https://x/mods|v1.0.0|c0ffee\n"
        "web-interface|WebInterface|https://x/mods|v1.0.0|c0ffee\n"
    )
    assert (p.src_modules / ".gitignore").read_text() == "*\n"


def test_generate_empty_selection(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    modules.generate(p, Registry.load(checkout), ["wifi"], "s", "r", "c")
    assert modules.generate(p, Registry.load(checkout), [], "https://x/mods", "v1.0.0", "c0ffee") == []
    assert sorted(f.name for f in p.src_modules.iterdir()) == [".gitignore", "Modules.h", "modules.lock"]
    text = (p.src_modules / "Modules.h").read_text()
    assert text.startswith("// Generated by xewe modules generate") and "#pragma once\n" in text
    assert "#include" not in text and "(os" not in text
    assert (p.src_modules / "modules.lock").read_text() == "# generated by xewe: slug|folder|source|ref|commit\n"


@pytest.mark.parametrize("value", ["", "none", " none "])
def test_expand_selection_none(checkout: Path, value: str) -> None:
    assert modules.expand_selection(Registry.load(checkout), value) == []


def test_failed_generate_keeps_old_modules(tmp_path: Path, checkout: Path) -> None:
    p = Paths(tmp_path / "proj")
    reg = Registry.load(checkout)
    modules.generate(p, reg, ["wifi"], "s", "r", "c")
    shutil.rmtree(next(checkout.rglob("*pins/src")))
    with pytest.raises(XeweError):
        modules.generate(p, Registry.load(checkout), ["pins"], "s", "r", "c")
    assert (p.src_modules / "Wifi").is_dir()


def test_real_properties_validate_clean(checkout: Path) -> None:
    assert modules.validate(Registry.load(checkout), core_ref="1.0.0") == []


@pytest.mark.parametrize(("slug", "key", "value", "message"), [
    ("wifi", "slug", "Wifi", "must match"),
    ("pins", "slug", "buttons", "is not unique"),
    ("pins", "slug", "pinz", "does not match its directory"),
    ("wifi", "id", "Wifi", "must match"),
    ("wifi", "id", "a_sixteen_chars_", "NVS namespace limit"),
    ("pins", "id", "buttons", "is not unique"),
    ("wifi", "folder", "wifi", "must match"),
    ("pins", "folder", "Buttons", "is not unique"),
    ("wifi", "folder", "Wireless", "does not exist"),
    ("wifi", "include", "Wifi.h", "must start with src/Wifi/"),
    ("wifi", "include", "src/Wifi/Missing.h", "does not exist"),
    ("wifi", "declare", "Wifi wifi(os)", "must look like"),
    ("wifi", "declare", "Wifi os(os);", "must not be 'os'"),
    ("pins", "declare", "Pins wifi(os);", "is not unique"),
    ("web-interface", "declare", "WebInterface web_interface(os, scheduler);", "neither 'os' nor"),
    ("wifi", "depends_modules", "wifi", "lists the module itself"),
    ("wifi", "depends_modules", "nope", "unknown module 'nope'"),
    ("wifi", "depends_modules", "scheduler", "dependency cycle"),
    ("wifi", "requires_core", "1.0.0", "must be '>=X.Y.Z'"),
    ("wifi", "requires_core", ">=2.0.0", "is not satisfied by core 1.0.0"),
    ("wifi", "requires_core", ">=0.5.0,<1.0.0", "is not satisfied"),
    ("wifi", "version", "1.0", "must be X.Y.Z"),
    ("wifi", "description", "", "description is empty"),
    ("wifi", "description", "x" * 101, "max 100"),
    ("wifi", "name", None, "missing key 'name'"),
    ("wifi", "depends_libraries", None, "missing key 'requires_core'"),
])
def test_every_rule_has_a_failing_fixture(tmp_path: Path, slug: str, key: str, value: str | None, message: str) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "legacy")
    _set(checkout, slug, key, value)
    errors = [str(p) for p in modules.validate(Registry.load(checkout), core_ref="1.0.0") if p.error]
    assert any(message in e for e in errors), errors


def test_warnings_do_not_fail(tmp_path: Path) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules")
    _set(checkout, "wifi", "colour", "blue")
    _set(checkout, "wifi", "declare", "Wireless wifi(os);")
    problems = modules.validate(Registry.load(checkout))
    assert problems and not any(p.error for p in problems)


def test_requires_core_non_semver_ref_is_skipped(tmp_path: Path) -> None:
    checkout = make_modules_checkout(tmp_path / "c", "modules")
    _set(checkout, "wifi", "requires_core", ">=9.0.0")
    assert modules.validate(Registry.load(checkout), core_ref="main") == []


def test_cli_validate_reference_layout(project: Paths, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    legacy = make_modules_checkout(tmp_path / "legacy", "legacy")
    assert main(["modules", "validate", str(legacy)]) == 0
    assert "6 modules, 0 errors" in capsys.readouterr().out
    _set(legacy, "wifi", "id", "a_sixteen_chars_")
    assert main(["modules", "validate", str(legacy)]) == 1


def test_cli_list_select_generate(project: Paths, capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["modules", "list"]) == 0
    out = capsys.readouterr().out
    assert "* wifi" in out and "  pins" in out
    assert main(["modules", "select", "scheduler"]) == 0
    assert 'selected = ["scheduler"]' in project.lock.read_text()
    assert (project.src_modules / "Modules.h").read_text().count("#include") == 3
    assert main(["modules", "select", "nope"]) == 2
    assert main(["modules", "select", "none"]) == 0
    assert "selected = []" in project.lock.read_text()
    assert "#include" not in (project.src_modules / "Modules.h").read_text()
    assert "src/modules: none" in capsys.readouterr().out
