import tomllib
from pathlib import Path

import pytest

from conftest import Port
from xewe.board import boards
from xewe.cli import main
from xewe.env import esptool
from xewe.env.project import Paths
from xewe.report import XeWeError

ESPTOOL5_OUTPUT = """esptool v5.3.1
Connected to ESP32-C6 on /dev/ttyACM0:
Chip type:          ESP32-C6 (QFN40) (revision v0.1)
Features:           Wi-Fi 6, BT 5 (LE), IEEE802.15.4, Single Core + LP Core, 160MHz
MAC:                40:4c:ca:ff:fe:12:34:56
Chip ID: 0x0000000d
Hard resetting via RTS pin...
"""


@pytest.fixture
def p(tmp_path: Path) -> Paths:
    (tmp_path / "xewe.toml").write_text("schema = 1\n")
    return Paths(tmp_path)


def test_parse_chip_id() -> None:
    assert esptool.parse_chip(ESPTOOL5_OUTPUT) == "c6"
    assert esptool.parse_chip("Detecting chip type... ESP32-S3") == "s3"
    assert esptool.parse_chip("Chip is ESP32-S2") == "s2"
    assert esptool.parse_chip("no answer") is None


def test_vid_pid_filter(p: Paths, ports: list[Port]) -> None:
    ports += [
        Port("/dev/ttyS0"),
        Port("/dev/ttyACM0", 0x303A, 0x1001, "AA"),
        Port("/dev/ttyUSB0", 0x10C4, 0xEA60, "BB"),
        Port("/dev/ttyUSB1", 0x1A86, 0x7523, "CC"),
        Port("/dev/ttyUSB2", 0x0403, 0x6001, "DD"),
        Port("/dev/ttyUSB3", 0x0403, 0x1234, "EE"),
        Port("/dev/ttyUSB4", 0x2341, 0x0043, "FF"),
    ]
    found = boards.scan(p, probe=False)
    assert [b.port for b in found] == ["/dev/ttyACM0", "/dev/ttyUSB0", "/dev/ttyUSB1", "/dev/ttyUSB2"]
    assert all(b.chip is None for b in found)


def test_probe_then_cache_by_serial_number(p: Paths, ports: list[Port], monkeypatch: pytest.MonkeyPatch) -> None:
    ports.append(Port("/dev/ttyACM0", 0x303A, 0x1001, "F0:F5"))
    calls: list[str] = []

    def probe(cmd: list[str], port: str) -> str:
        calls.append(port)
        return "c6"

    monkeypatch.setattr(esptool, "chip_id", probe)
    assert boards.scan(p, esptool_cmd=lambda: ["esptool"])[0].chip == "c6"
    again = boards.scan(p, esptool_cmd=lambda: ["esptool"])[0]
    assert again.chip == "c6" and again.detected_by == "cache"
    assert calls == ["/dev/ttyACM0"]
    data = tomllib.loads(p.boards_toml.read_text())
    assert data["board"][0]["serial_number"] == "F0:F5" and data["board"][0]["vid"] == "303a"


def test_no_board(p: Paths, ports: list[Port]) -> None:
    assert boards.select(p) is None


def test_one_board(p: Paths, ports: list[Port]) -> None:
    ports.append(Port("/dev/ttyACM0", 0x303A, 0x1001))
    assert boards.select(p, probe=False).port == "/dev/ttyACM0"


def test_several_boards(p: Paths, ports: list[Port]) -> None:
    ports += [Port("/dev/ttyACM0", 0x303A, 0x1001, "A"), Port("/dev/ttyACM1", 0x303A, 0x1001, "B")]
    with pytest.raises(XeWeError) as exc:
        boards.select(p, probe=False)
    assert exc.value.code == 4
    p.boards_toml.write_text('schema = 1\n[[board]]\nport = "x"\nserial_number = "B"\nchip = "s3"\n')
    assert boards.select(p, chip="s3", probe=False).port == "/dev/ttyACM1"


def test_explicit_missing_port_is_exit_4(p: Paths, ports: list[Port]) -> None:
    with pytest.raises(XeWeError) as exc:
        boards.select(p, port="/dev/does-not-exist")
    assert exc.value.code == 4


def test_override_precedence(p: Paths, ports: list[Port], monkeypatch: pytest.MonkeyPatch) -> None:
    ports += [Port("/dev/ttyACM0", 0x303A, 0x1001), Port("/dev/ttyUSB9", 0x2341, 0x0043)]
    boards.set_override(p, "/dev/ttyUSB9", "s3", clear=False)
    board = boards.select(p, probe=False)
    assert (board.port, board.chip, board.detected_by) == ("/dev/ttyUSB9", "s3", "override")
    monkeypatch.setenv("XEWE_PORT", "/dev/ttyACM0")
    assert boards.select(p, probe=False).port == "/dev/ttyACM0"
    assert boards.select(p, port="/dev/ttyUSB9", probe=False).port == "/dev/ttyUSB9"


def test_override_absent_from_system_means_scan(p: Paths, ports: list[Port]) -> None:
    boards.set_override(p, "/dev/ttyGONE", "c3", clear=False)
    assert boards.select(p) is None


def test_override_preserved_across_rewrites(p: Paths, ports: list[Port]) -> None:
    boards.set_override(p, "/dev/ttyACM0", "c3", clear=False)
    ports.append(Port("/dev/ttyACM1", 0x303A, 0x1001))
    boards.scan(p, probe=False)
    data = tomllib.loads(p.boards_toml.read_text())
    assert data["override"] == {"port": "/dev/ttyACM0", "chip": "c3"}
    assert p.boards_toml.read_text().startswith("# generated by xewe; [override] is yours and is kept")
    boards.set_override(p, None, None, clear=True)
    assert "override" not in tomllib.loads(p.boards_toml.read_text())


def test_resolve_chip_rule(monkeypatch: pytest.MonkeyPatch) -> None:
    board = boards.Board("/dev/x", chip="s3")
    assert boards.resolve_chip("c6", board, "c3") == "c6"
    assert boards.resolve_chip(None, board, "c3") == "s3"
    assert boards.resolve_chip(None, None, "c6") == "c6"
    assert boards.resolve_chip(None, boards.Board("/dev/x", chip="s2"), None) == "c3"
    monkeypatch.setenv("XEWE_CHIP", "s3")
    assert boards.resolve_chip(None, None, "c3") == "s3"


def test_cli_boards_no_board(project: Paths, capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["boards"]) == 0
    assert capsys.readouterr().out.strip() == "no board attached"
    assert main(["boards", "--require-board"]) == 4


def test_cli_boards_lists_and_sets(project: Paths, ports: list[Port], capsys: pytest.CaptureFixture[str]) -> None:
    ports.append(Port("/dev/ttyACM0", 0x303A, 0x1001, "SN1", "USB JTAG/serial debug unit"))
    assert main(["boards", "--no-probe"]) == 0
    assert "/dev/ttyACM0" in capsys.readouterr().out
    assert main(["boards", "--set-port", "/dev/ttyACM0", "--set-chip", "c3"]) == 0
    assert main(["boards", "--set-chip", "c3"]) == 2
