"""``run.sh``: the project's run script, generated by ``xewe setup`` so it never drifts from the tools.

``xewe setup`` writes ``<project>/run.sh`` from ``RUN_SH`` (the installed tools version and the
manifest's default chip filled in) when the file is missing or carries ``GENERATED_MARK`` (or is
the old reference copy, ``LEGACY_RUN_SH``); a hand-written ``run.sh`` is never replaced, setup
prints a note instead. The template repo commits exactly what setup generates, so a fresh clone
works before setup too.
"""

from __future__ import annotations

import os
from pathlib import Path

from xewe import __version__
from xewe.env.project import Paths, write_atomic
from xewe.report import log, result

GENERATED_MARK = "# generated by xewe setup; do not edit"

RUN_SH = """\
#!/usr/bin/env bash
{mark} (xewe-os-tools {version}; ./setup.sh rewrites it).
# run.sh: build, erase the flash, flash, then listen on the serial console (`xewe run`).
#   chip: {chip} unless --chip C (default from xewe.toml [project] chip)
#   every run erases the whole flash, NVS included (device name, Wi-Fi, module choices), so the
#   board boots as new; --keep-nvs skips the erase. All flags: ./run.sh --help
set -euo pipefail
ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
PY="${{ROOT}}/build/tools/.venv/bin/python"
[[ -x "${{PY}}" ]] || {{ echo "error: run ./setup.sh first" >&2; exit 3; }}
exec "${{PY}}" -m xewe --project "${{ROOT}}" run "$@"
"""

LEGACY_RUN_SH = """\
#!/usr/bin/env bash
# run.sh: reference ./run.sh for XeWe OS projects: build, flash, listen (`xewe run`).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PY="${ROOT}/build/tools/.venv/bin/python"
[[ -x "${PY}" ]] || { echo "error: run ./setup.sh first" >&2; exit 3; }
exec "${PY}" -m xewe --project "${ROOT}" run "$@"
"""
"""The reference ``run.sh`` of tools 0.1.1 (before setup generated it); replaced like a generated one."""


def render(chip: str, version: str = __version__) -> str:
    """Contents of the generated ``run.sh`` for a project whose default chip is ``chip``."""
    return RUN_SH.format(mark=GENERATED_MARK, version=version, chip=chip)


def is_generated(text: str) -> bool:
    """True when ``text`` is a ``run.sh`` setup may replace: it carries the mark, or is the legacy copy."""
    return text == LEGACY_RUN_SH or any(line.startswith(GENERATED_MARK) for line in text.splitlines()[:3])


def write(p: Paths, chip: str) -> bool:
    """Write ``<project>/run.sh`` (mode 755) unless a hand-written one is there; True when written or current."""
    path = p.root / "run.sh"
    want = render(chip)
    if path.is_file() or path.is_symlink():
        have = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
        if have == want:
            _executable(path)
            log.debug("run.sh is current")
            return True
        if not is_generated(have):
            result(f"note: {p.rel(path)} is hand-written (no '{GENERATED_MARK}' line); kept as is. "
                   "Delete it and run ./setup.sh again for the generated one.")
            return False
    write_atomic(path, want)
    _executable(path)
    log.info("wrote %s (generated; chip %s)", p.rel(path), chip)
    return True


def _executable(path: Path) -> None:
    mode = path.stat().st_mode
    if mode & 0o111 != 0o111:
        os.chmod(path, mode | 0o755)
