"""Board detection, selection and ``build/config/boards.toml`` (SPEC §5)."""

from __future__ import annotations

import datetime as dt
import os
import tomllib
from collections.abc import Callable
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from serial.tools import list_ports

from xewe.build.chips import CHIPS, DEFAULT_CHIP
from xewe.env import esptool
from xewe.env.project import Paths, write_atomic
from xewe.modules import tomlw
from xewe.report import EXIT_NO_BOARD, XeweError, board_disabled, log

SCHEMA = 1
HEADER = "# generated by xewe; [override] is yours and is kept"

# VID -> allowed PIDs (None = any PID of that vendor)
KNOWN_USB: dict[str, set[str] | None] = {
    "303a": None,  # Espressif native USB-Serial/JTAG and USB-OTG CDC
    "10c4": {"ea60"},  # CP210x
    "1a86": {"7523", "55d3"},  # CH340, CH343
    "0403": {"6001", "6010", "6015"},  # FTDI
}


@dataclass
class Board:
    """One candidate board."""

    port: str
    chip: str | None = None
    vid: str = ""
    pid: str = ""
    serial_number: str = ""
    description: str = ""
    detected_by: str = ""
    last_seen: str = ""


def _now() -> str:
    return dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _hex(value: int | None) -> str:
    return f"{value:04x}" if value is not None else ""


def is_known(vid: str, pid: str) -> bool:
    """True when VID:PID is a known ESP USB interface."""
    if vid not in KNOWN_USB:
        return False
    pids = KNOWN_USB[vid]
    return pids is None or pid in pids


def _port_board(info: Any) -> Board:
    return Board(
        port=info.device,
        vid=_hex(info.vid),
        pid=_hex(info.pid),
        serial_number=info.serial_number or "",
        description=info.description or "",
        last_seen=_now(),
    )


def read_toml(p: Paths) -> dict[str, Any]:
    """Contents of boards.toml ({} when missing or unreadable)."""
    try:
        return tomllib.loads(p.boards_toml.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return {}


def write_toml(p: Paths, boards: list[Board], override: dict[str, str] | None = None) -> None:
    """Rewrite boards.toml with ``boards``, keeping the existing ``[override]`` unless given."""
    if override is None:
        override = read_toml(p).get("override", {})
    data: dict[str, Any] = {"schema": SCHEMA}
    if override:
        data["override"] = override
    data["board"] = [{k: v for k, v in asdict(b).items() if v not in (None, "")} for b in boards]
    write_atomic(p.boards_toml, tomlw.dumps(data, header=HEADER))


def port_exists(port: str) -> bool:
    """True when ``port`` is listed by pyserial or exists as a device node (never with XEWE_NO_BOARD)."""
    if board_disabled():
        return False
    return any(info.device == port for info in list_ports.comports()) or Path(port).exists()


def scan(
    p: Paths, probe: bool = True, esptool_cmd: Callable[[], list[str]] | None = None, port: str | None = None
) -> list[Board]:
    """Candidate boards: known VID:PID ports (or just ``port``), chip from cache or esptool probe.

    With board access disabled (``XEWE_NO_BOARD``) nothing is listed, probed or written.
    """
    if board_disabled():
        return []
    cached = {
        b.get("serial_number"): b.get("chip")
        for b in read_toml(p).get("board", [])
        if b.get("serial_number") and b.get("chip")
    }
    boards: list[Board] = []
    for info in list_ports.comports():
        board = _port_board(info)
        if port is not None:
            if board.port != port:
                continue
        elif not board.vid or not is_known(board.vid, board.pid):
            continue
        boards.append(board)
    if port is not None and not boards:
        boards.append(Board(port=port, last_seen=_now()))
    for board in boards:
        if board.serial_number in cached:
            board.chip, board.detected_by = cached[board.serial_number], "cache"
        elif probe and esptool_cmd is not None:
            try:
                chip = esptool.chip_id(esptool_cmd(), board.port)
            except XeweError as exc:
                log.warning("cannot probe %s: %s", board.port, exc)
                chip = None
            if chip:
                board.chip, board.detected_by = chip, "esptool"
                if chip not in CHIPS:
                    log.warning("%s: ESP32-%s is not supported (c3, c6, s3 only)", board.port, chip.upper())
    write_toml(p, boards)
    return boards


def select(
    p: Paths,
    chip: str | None = None,
    port: str | None = None,
    probe: bool = True,
    esptool_cmd: Callable[[], list[str]] | None = None,
) -> Board | None:
    """The board to use, or None when no board is attached.

    Precedence: ``port``/``chip`` arguments, ``XEWE_PORT``/``XEWE_CHIP``, ``[override]`` in
    boards.toml, then a scan. A named port that does not exist is exit 4, as is a choice
    between several boards that ``chip`` does not settle. With board access disabled
    (``XEWE_NO_BOARD``) the answer is always None and no port is looked at.
    """
    if board_disabled():
        return None
    port = port or os.environ.get("XEWE_PORT") or None
    chip = chip or os.environ.get("XEWE_CHIP") or None
    if port is not None:
        if not port_exists(port):
            raise XeweError(f"port {port} not found", EXIT_NO_BOARD)
        return scan(p, probe, esptool_cmd, port=port)[0]

    override = read_toml(p).get("override", {})
    if override.get("port") and port_exists(override["port"]):
        board = scan(p, probe and not override.get("chip"), esptool_cmd, port=override["port"])[0]
        if override.get("chip"):
            board.chip, board.detected_by = override["chip"], "override"
        return board

    boards = scan(p, probe, esptool_cmd)
    if not boards:
        return None
    if len(boards) == 1:
        return boards[0]
    matching = [b for b in boards if chip and b.chip == chip]
    if len(matching) == 1:
        return matching[0]
    raise XeweError("several boards attached; pass --port", EXIT_NO_BOARD)


def resolve_chip(chip_flag: str | None, board: Board | None, lock_chip: str | None) -> str:
    """Chip rule: --chip/XEWE_CHIP, then the attached board's chip, then [project] chip, then c3."""
    chip = chip_flag or os.environ.get("XEWE_CHIP")
    if chip:
        return chip
    if board is not None and board.chip in CHIPS:
        return board.chip
    return lock_chip or DEFAULT_CHIP


def set_override(p: Paths, port: str | None, chip: str | None, clear: bool) -> dict[str, str]:
    """Update ``[override]`` in boards.toml and return it."""
    data = read_toml(p)
    override: dict[str, str] = {} if clear else dict(data.get("override", {}))
    if port:
        override["port"] = port
    if chip:
        override["chip"] = chip
    boards = [Board(**{k: v for k, v in b.items() if k in Board.__dataclass_fields__}) for b in data.get("board", [])]
    write_toml(p, boards, override)
    return override
