#!/usr/bin/env bash
# generated by xewe setup; do not edit (xewe-os-tools 0.1.1; ./setup.sh rewrites it).
# run.sh: build, erase the flash, flash, then listen on the serial console (`xewe run`).
#   chip: c3 unless --chip C (default from xewe.toml [project] chip)
#   every run erases the whole flash, NVS included (device name, Wi-Fi, module choices), so the
#   board boots as new; --keep-nvs skips the erase. All flags: ./run.sh --help
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PY="${ROOT}/build/tools/.venv/bin/python"
[[ -x "${PY}" ]] || { echo "error: run ./setup.sh first" >&2; exit 3; }
exec "${PY}" -m xewe --project "${ROOT}" run "$@"
