"""``build/build_config.toml``: what setup installed and where (SPEC §6).

Paths are stored relative to ``build/``. The only absolute entries are the ones that point
outside the project on purpose: ``--arduino-data`` and an ``XEWE_ARDUINO_CLI`` override.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from xewe import __version__, tomlw
from xewe.project import Paths, write_atomic
from xewe.report import EXIT_NOT_SETUP, XeweError

SCHEMA = 1
HEADER = "# generated by xewe setup; do not edit"


@dataclass
class BuildConfig:
    """Parsed build_config.toml."""

    tools_version: str = __version__
    setup_completed: str = ""
    paths: dict[str, str] = field(default_factory=dict)
    installed: dict[str, Any] = field(default_factory=dict)

    def path(self, p: Paths, key: str) -> Path | None:
        """Resolve ``[paths] key`` against build/ (None when not recorded)."""
        stored = self.paths.get(key)
        return p.from_build(stored) if stored else None

    def arduino_data(self, p: Paths) -> Path:
        """The arduino-cli data directory (default build/arduino15)."""
        return self.path(p, "arduino_data") or p.default_arduino_data


def load(p: Paths) -> BuildConfig | None:
    """Read build_config.toml, or None when it is missing or unreadable."""
    if not p.build_config.is_file():
        return None
    try:
        data = tomllib.loads(p.build_config.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return None
    if data.get("schema") != SCHEMA:
        return None
    return BuildConfig(
        tools_version=str(data.get("tools_version", "")),
        setup_completed=str(data.get("setup_completed", "")),
        paths=dict(data.get("paths", {})),
        installed=dict(data.get("installed", {})),
    )


def require(p: Paths) -> BuildConfig:
    """Like :func:`load`, but a missing file is exit 3."""
    cfg = load(p)
    if cfg is None:
        raise XeweError("not set up (build/build_config.toml missing or incomplete); run ./setup.sh", EXIT_NOT_SETUP)
    return cfg


def save(p: Paths, cfg: BuildConfig) -> None:
    """Write build_config.toml atomically."""
    data: dict[str, Any] = {
        "schema": SCHEMA,
        "tools_version": cfg.tools_version,
        "setup_completed": cfg.setup_completed,
        "paths": cfg.paths,
        "installed": cfg.installed,
    }
    write_atomic(p.build_config, tomlw.dumps(data, header=HEADER))
