"""Modules checkout: registry, dependency resolution, ``src/modules/`` generation, validation (SPEC §10).

Two layouts are read: ``modules/<slug>/module.properties`` (the modules repo, D4) and, until the
modules are ported (O9), the old one-repo-per-module layout ``xewe-os-module-<slug>/`` (or a
single module repo whose root holds ``module.properties``).
"""

from __future__ import annotations

import os
import re
import shutil
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from xewe.project import Paths
from xewe.report import EXIT_FAIL, EXIT_USAGE, XeweError, log

LEGACY_PREFIX = "xewe-os-module-"
REQUIRED_KEYS = (
    "slug", "id", "name", "version", "description", "folder", "include", "declare",
    "depends_modules", "requires_core",
)
LEGACY_KEYS = ("repo", "depends_libraries")
MODULES_H_HEADER = (
    "// Generated by xewe modules generate; do not edit. Re-run ./setup.sh or "
    "`xewe modules select` to change modules.\n"
    "// Included by the sketch after `os`; modules are declared in dependency order.\n"
    "#pragma once\n"
)
LOCK_HEADER = "# generated by xewe: slug|folder|source|ref|commit"
CATALOGUE = "libraries.toml"
"""Library catalogue at the root of the modules checkout: ``[Name] repo = "...", ref = "..."``."""
CORE_LIBRARIES = frozenset({"XeWeCore", "XeWeOS"})
"""The core library (current and legacy name): installed by setup itself, never from the catalogue."""
FROM_LOCK = "xewe.lock"
FROM_CATALOGUE = "modules catalogue"

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")
FOLDER_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")
DECLARE_RE = re.compile(r"^(\w+)\s+(\w+)\s*\((.*)\)\s*;$")
IDENT_RE = re.compile(r"^[A-Za-z_]\w*$")
VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")
REQUIRES_RE = re.compile(r"^>=\s*(\d+\.\d+\.\d+)(?:\s*,\s*<\s*(\d+\.\d+\.\d+))?$")
MAX_ID_LEN = 15  # NVS namespace limit


def parse_properties(text: str) -> tuple[dict[str, str], list[str]]:
    """``key=value`` lines: first occurrence wins (like the old ``prop()``); also returns all keys."""
    props: dict[str, str] = {}
    keys: list[str] = []
    for line in text.splitlines():
        if "=" not in line or line.lstrip().startswith("#"):
            continue
        key, value = line.split("=", 1)
        keys.append(key)
        props.setdefault(key, value)
    return props, keys


@dataclass
class Module:
    """One module in a checkout."""

    dir: Path
    dir_slug: str
    props: dict[str, str]
    keys: list[str] = field(default_factory=list)

    @classmethod
    def read(cls, directory: Path, dir_slug: str) -> Module:
        props, keys = parse_properties((directory / "module.properties").read_text(encoding="utf-8"))
        return cls(directory, dir_slug, props, keys)

    @property
    def slug(self) -> str:
        return self.props.get("slug", "")

    @property
    def folder(self) -> str:
        return self.props.get("folder", "")

    @property
    def deps(self) -> list[str]:
        return [d for d in re.split(r"[,\s]+", self.props.get("depends_modules", "")) if d]

    @property
    def libraries(self) -> list[str]:
        """Names in ``depends_libraries`` (a ``(>=x.y.z)`` suffix is ignored), core library excluded."""
        names = (re.sub(r"\(.*?\)", "", x).strip() for x in self.props.get("depends_libraries", "").split(","))
        return [n for n in names if n and n not in CORE_LIBRARIES]

    @property
    def tests_dir(self) -> Path:
        return self.dir / "tests"

    def declared(self) -> tuple[str, str, list[str]] | None:
        """(type, variable, arguments) of ``declare=``, or None when it does not parse."""
        m = DECLARE_RE.match(self.props.get("declare", "").strip())
        if not m:
            return None
        args = [a.strip() for a in m[3].split(",") if a.strip()]
        return m[1], m[2], args


class Registry:
    """All modules of a checkout, by slug."""

    def __init__(self, root: Path, modules: list[Module]) -> None:
        self.root = root
        self.all = modules
        self.by_slug: dict[str, Module] = {}
        for module in modules:
            self.by_slug.setdefault(module.slug, module)

    @classmethod
    def load(cls, root: Path) -> Registry:
        """Discover modules under ``root`` (both layouts)."""
        if not root.is_dir():
            raise XeweError(f"modules checkout {root} not found; run ./setup.sh", EXIT_FAIL)
        found: list[Module] = []
        new_layout = root / "modules"
        if new_layout.is_dir():
            for d in sorted(new_layout.iterdir()):
                if (d / "module.properties").is_file():
                    found.append(Module.read(d, d.name))
        for d in sorted(root.glob(f"{LEGACY_PREFIX}*")):
            if (d / "module.properties").is_file():
                found.append(Module.read(d, d.name[len(LEGACY_PREFIX):]))
        if (root / "module.properties").is_file():
            found.append(Module.read(root, root.name.removeprefix(LEGACY_PREFIX)))
        return cls(root, found)

    @staticmethod
    def layout_note() -> str:
        """The layouts discovery looks for, for the "no modules found" warning."""
        return (f"modules/<slug>/module.properties (new layout) or {LEGACY_PREFIX}<slug>/module.properties "
                "(old layout)")

    def slugs(self) -> list[str]:
        """Slugs in discovery order."""
        return list(self.by_slug)

    def get(self, slug: str) -> Module:
        try:
            return self.by_slug[slug]
        except KeyError:
            raise XeweError(f"module '{slug}' not found in {self.root}", EXIT_USAGE) from None

    def resolve(self, selected: list[str], quiet: bool = False) -> list[Module]:
        """Depth-first over ``selected``, dependencies first (the old ``visit()`` order)."""
        order: list[Module] = []
        done: set[str] = set()
        visiting: list[str] = []
        announced: set[str] = set()

        def visit(slug: str) -> None:
            if slug in done:
                return
            if slug in visiting:
                raise XeweError(f"dependency cycle through module '{slug}'", EXIT_FAIL)
            module = self.get(slug)
            visiting.append(slug)
            for dep in module.deps:
                if dep not in selected and dep not in announced and not quiet:
                    announced.add(dep)
                    log.info("%s requires %s; adding it", slug, dep)
                visit(dep)
            visiting.remove(slug)
            done.add(slug)
            order.append(module)

        for slug in selected:
            visit(slug)
        return order


def load_catalogue(root: Path) -> dict[str, tuple[str, str]]:
    """``libraries.toml`` of a modules checkout as ``{name: (repo, ref)}`` ({} when absent)."""
    path = root / CATALOGUE
    if not path.is_file():
        return {}
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise XeweError(f"{path}: invalid TOML: {exc}", EXIT_FAIL) from None
    out: dict[str, tuple[str, str]] = {}
    for name, spec in data.items():
        if (not isinstance(spec, dict) or set(spec) != {"repo", "ref"}
                or not all(isinstance(v, str) and v for v in spec.values())):
            raise XeweError(f'{path}: [{name}] must have exactly repo = "..." and ref = "..."', EXIT_FAIL)
        out[name] = (spec["repo"], spec["ref"])
    return out


@dataclass
class Library:
    """One library setup installs: where it is pinned and which modules need it."""

    name: str
    repo: str
    ref: str
    origin: str
    """FROM_LOCK (``[libraries]`` of xewe.lock) or FROM_CATALOGUE (the modules checkout's libraries.toml)."""
    needed_by: list[str] = field(default_factory=list)


def library_plan(
    lock_libraries: dict[str, tuple[str, str]], order: list[Module], catalogue: dict[str, tuple[str, str]]
) -> tuple[list[Library], list[str]]:
    """Libraries to install: every ``[libraries]`` entry of the lock, plus each ``depends_libraries``
    name of the resolved modules ``order`` that the lock does not pin, from the catalogue.

    The lock wins over the catalogue for the same name. Returns (libraries, warnings); a name in
    neither is a warning (it is not installed).
    """
    plan = {name: Library(name, repo, ref, FROM_LOCK) for name, (repo, ref) in lock_libraries.items()}
    warnings: list[str] = []
    for module in order:
        for name in module.libraries:
            if name not in plan:
                if name not in catalogue:
                    warnings.append(f"library {name} (needed by module {module.slug}) is neither in xewe.lock "
                                    f"[libraries] nor in the modules {CATALOGUE}; not installed")
                    continue
                repo, ref = catalogue[name]
                plan[name] = Library(name, repo, ref, FROM_CATALOGUE)
            plan[name].needed_by.append(module.slug)
    return list(plan.values()), list(dict.fromkeys(warnings))


NONE_WORDS = ("", "none")


def expand_selection(registry: Registry, value: str) -> list[str]:
    """``all``, ``none``/empty (no modules), or a comma/space separated list of slugs (each must exist)."""
    if value.strip() == "all":
        return registry.slugs()
    if value.strip() in NONE_WORDS:
        return []
    slugs = [s for s in re.split(r"[,\s]+", value) if s]
    for slug in slugs:
        registry.get(slug)
    return slugs


def render_modules_h(order: list[Module]) -> str:
    """Contents of ``src/modules/Modules.h`` (header and ``#pragma once`` only when nothing is selected)."""
    if not order:
        return f"{MODULES_H_HEADER}\n// no modules selected\n"
    includes = "".join(f'#include "{m.props["include"].removeprefix("src/")}"\n' for m in order)
    declares = "".join(f"{m.props['declare']}\n" for m in order)
    return f"{MODULES_H_HEADER}\n{includes}\n{declares}"


def render_modules_lock(order: list[Module], source: str, ref: str, commit: str) -> str:
    """Contents of ``src/modules/modules.lock``."""
    lines = [LOCK_HEADER] + [f"{m.slug}|{m.folder}|{source}|{ref}|{commit}" for m in order]
    return "\n".join(lines) + "\n"


def generate(p: Paths, registry: Registry, selected: list[str], source: str, ref: str, commit: str) -> list[Module]:
    """Rebuild ``src/modules/`` from ``selected`` (staged in build/gen/modules.tmp, then swapped).

    An empty ``selected`` is valid: ``Modules.h`` then declares nothing and ``modules.lock`` holds
    only its header line.
    """
    order = registry.resolve(selected)
    stage = p.gen / "modules.tmp"
    shutil.rmtree(stage, ignore_errors=True)
    stage.mkdir(parents=True)
    for module in order:
        folder = module.folder
        src = module.dir / "src" / folder
        if not FOLDER_RE.match(folder) or not src.is_dir():
            raise XeweError(f"module '{module.slug}': src/{folder} not found in {module.dir}", EXIT_FAIL)
        if (stage / folder).exists():
            raise XeweError(f"module '{module.slug}': folder '{folder}' is used by another module", EXIT_FAIL)
        if not module.props.get("include") or not module.props.get("declare"):
            raise XeweError(f"module '{module.slug}': module.properties needs include= and declare=", EXIT_FAIL)
        shutil.copytree(src, stage / folder, ignore=shutil.ignore_patterns(".git"))
        log.info("installed src/modules/%s  (%s %s)", folder, module.slug, module.props.get("version", "?"))
    (stage / "Modules.h").write_text(render_modules_h(order), encoding="utf-8")
    (stage / ".gitignore").write_text("*\n", encoding="utf-8")
    (stage / "modules.lock").write_text(render_modules_lock(order, source, ref, commit), encoding="utf-8")
    p.src_modules.parent.mkdir(parents=True, exist_ok=True)
    old = p.gen / "modules.old"
    shutil.rmtree(old, ignore_errors=True)
    if p.src_modules.exists():
        os.replace(p.src_modules, old)
    os.replace(stage, p.src_modules)
    shutil.rmtree(old, ignore_errors=True)
    return order


# ---------------------------------------------------------------------------- validation


@dataclass
class Problem:
    """One validation finding."""

    where: str
    message: str
    error: bool = True

    def __str__(self) -> str:
        return f"{'error' if self.error else 'warning'}: {self.where}: {self.message}"


def _semver(text: str) -> tuple[int, int, int] | None:
    m = VERSION_RE.match(text.removeprefix("v"))
    return (int(m[1]), int(m[2]), int(m[3])) if m else None


def _transitive_deps(registry: Registry, module: Module) -> set[str]:
    seen: set[str] = set()
    stack = list(module.deps)
    while stack:
        slug = stack.pop()
        if slug in seen or slug not in registry.by_slug:
            continue
        seen.add(slug)
        stack.extend(registry.by_slug[slug].deps)
    return seen


def _cycle(registry: Registry, start: str) -> bool:
    stack = list(registry.by_slug[start].deps)
    seen: set[str] = set()
    while stack:
        slug = stack.pop()
        if slug == start:
            return True
        if slug in seen or slug not in registry.by_slug:
            continue
        seen.add(slug)
        stack.extend(registry.by_slug[slug].deps)
    return False


def validate(registry: Registry, core_ref: str | None = None) -> list[Problem]:
    """Apply every rule of SPEC §10 to every module of ``registry``."""
    problems: list[Problem] = []
    counts: dict[tuple[str, str], int] = {}
    for module in registry.all:
        for key in ("slug", "id", "folder"):
            value = module.props.get(key, "")
            counts[(key, value)] = counts.get((key, value), 0) + 1
        decl = module.declared()
        if decl:
            counts[("var", decl[1])] = counts.get(("var", decl[1]), 0) + 1

    for module in registry.all:
        where = module.slug or module.dir.name
        props = module.props

        def err(msg: str, error: bool = True) -> None:
            problems.append(Problem(where, msg, error))

        for key in REQUIRED_KEYS:
            if key not in props:
                if key == "requires_core" and "depends_libraries" in props:
                    continue
                err(f"missing key '{key}'")
        for key in dict.fromkeys(module.keys):
            if key not in REQUIRED_KEYS and key not in LEGACY_KEYS:
                err(f"unknown key '{key}'", error=False)

        slug = props.get("slug", "")
        if "slug" in props:
            if not SLUG_RE.match(slug):
                err(f"slug '{slug}' must match {SLUG_RE.pattern}")
            if counts[("slug", slug)] > 1:
                err(f"slug '{slug}' is not unique")
            if slug != module.dir_slug:
                err(f"slug '{slug}' does not match its directory '{module.dir.name}'")

        mid = props.get("id", "")
        if "id" in props:
            if not ID_RE.match(mid):
                err(f"id '{mid}' must match {ID_RE.pattern}")
            if len(mid) > MAX_ID_LEN:
                err(f"id '{mid}' is {len(mid)} chars; the NVS namespace limit is {MAX_ID_LEN}")
            if counts[("id", mid)] > 1:
                err(f"id '{mid}' is not unique")

        folder = props.get("folder", "")
        if "folder" in props:
            if not FOLDER_RE.match(folder):
                err(f"folder '{folder}' must match {FOLDER_RE.pattern}")
            if counts[("folder", folder)] > 1:
                err(f"folder '{folder}' is not unique")
            if not (module.dir / "src" / folder).is_dir():
                err(f"src/{folder}/ does not exist")

        include = props.get("include", "")
        if "include" in props:
            if not include.startswith(f"src/{folder}/"):
                err(f"include '{include}' must start with src/{folder}/")
            elif not (module.dir / include).is_file():
                err(f"include '{include}' does not exist")

        if "declare" in props:
            decl = module.declared()
            if decl is None:
                err(f"declare '{props['declare']}' must look like 'Type variable(os, ...);'")
            else:
                dtype, var, args = decl
                if dtype != folder:
                    err(f"declare type '{dtype}' differs from folder '{folder}'", error=False)
                if var == "os":
                    err("declare variable must not be 'os'")
                elif counts[("var", var)] > 1:
                    err(f"declare variable '{var}' is not unique")
                allowed = {"os"} | {
                    d for dep in _transitive_deps(registry, module)
                    if (d := (registry.by_slug[dep].declared() or ("", "", []))[1])
                }
                for arg in args:
                    if IDENT_RE.match(arg) and arg not in allowed:
                        err(f"declare argument '{arg}' is neither 'os' nor a module in depends_modules")

        for dep in module.deps:
            if dep == slug:
                err("depends_modules lists the module itself")
            elif dep not in registry.by_slug:
                err(f"depends_modules: unknown module '{dep}'")
        if slug in registry.by_slug and registry.by_slug[slug] is module and _cycle(registry, slug):
            err(f"dependency cycle through module '{slug}'")

        if "requires_core" in props:
            m = REQUIRES_RE.match(props["requires_core"].strip())
            if not m:
                err(f"requires_core '{props['requires_core']}' must be '>=X.Y.Z' or '>=X.Y.Z,<X.Y.Z'")
            elif core_ref is not None:
                have = _semver(core_ref)
                if have is None:
                    log.info("%s: requires_core not checked (core ref '%s' is not X.Y.Z)", where, core_ref)
                else:
                    low = _semver(m[1])
                    high = _semver(m[2]) if m[2] else None
                    if (low and have < low) or (high and have >= high):
                        err(f"requires_core '{props['requires_core']}' is not satisfied by core {core_ref}")

        if "version" in props and not VERSION_RE.match(props["version"]):
            err(f"version '{props['version']}' must be X.Y.Z")
        if "description" in props:
            desc = props["description"]
            if not desc.strip():
                err("description is empty")
            elif len(desc) > 100:
                err(f"description is {len(desc)} chars (max 100)")
    return problems
